<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void 
    {
        Schema::create('books', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('author_id');
             $table->unsignedBigInteger('cat_id');
            $table->string('bookname');
            $table->string('photo');   
            $table->integer('price');
            $table->text('details');
            $table->string('pdf');
            $table->string('statuse');
            $table->foreign('author_id') 
            ->references('id')
            ->on('users')
            ->constrained()
            ->cascadeOnDelete();
            $table->foreign('cat_id') 
            ->references('id')
            ->on('categories')
            ->constrained()
            ->cascadeOnDelete();
            $table->timestamps();
        });

        DB::table('books')->insert( 
           [ ['author_id' => '2', 'cat_id' => '1','bookname'=>'Too Late','photo'=>'Capture.PNG','price'=>1027.00,'details'=>'Sloan will go through hell and back for those she loves. And she does so, every single day. Caught up with the alluring Asa Jackson, a notorious drug trafficker, Sloan has finally found a lifeline to cling to, even if it`s meant compromising her morals. She was in dire straits trying to pay for her brother’s care until she met Asa. But as Sloan became emotionally and economically reliant on him, he in turn developed a disturbing obsession with her—one that becomes increasingly dangerous every day.','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '1','bookname'=>'Hopeless','photo'=>'Capture1.PNG','price'=>1027.00,'details'=>'That`s what Sky Davis realizes after she meets Dean Holder. A guy with a reputation that rivals her own and an uncanny ability to invoke feelings in her she’s never had before. He terrifies her and captivates her all in the span of their first encounter.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '2','bookname'=>'كن أنت','photo'=>'41JRnKKORRL._SY445_SX342_.jpg','price'=>320.00,'details'=>'كل نفس على الأرض تسعى بوعي او من دون وعي للعودة إلى أصلها الروحي، وهنا يلبي الكتاب هذا المطلب الملتهب، ليعمل كالمرشد لك في رحلتك الداخلية إلى أصلك الواحد. لا يسعى الكتاب ان يكون جرعة تحفيزية، أو حتى ليرمي ببعض التقنيات في التنمية البشرية، وانما هو مرشد صادق وشجاع في صلب اكتشاف الذات والتعبير الصادق عنها. يعرف د.إيهاب، الكاتب، في أسلوبه المتكامل الذي يحاكي الروح والعملية على حد سواء، ومن خلال المزج بين تعاليم الوعي والقصص والأمثلة، ليقدم لك خطاب شمولي لنهضتك ونهضة الجنس الإنساني ككل. قد قام إيهاب من خلال رسالة كن انت، والتي شاهدها الملايين حول العالم، بمشاركة رسائل عميقة وملهمة في صلب اكتشاف الذات والتمكين النفسي، ليأتي هذا الكتاب كزبدة فلسفته البسيطة في الحياة، ليساعدك أن تعيش رسالتك الحقيقة على الأرض','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '2','bookname'=>'لا تحزن','photo'=>'2750180.jpg','price'=>550.00,'details'=>'خطّ المؤلف في هذه الصفحات علاجاً لمن عاش ضائقة أو ألمّ به حزن أو هم، أو طاف به طائف من مصيبة، أو أقضي مضجعه أرق، وشرد نومه قلق. وأينا يخلو من ذلك. هنا في طيات هذا الكتاب آيات وأبيات، صور وعبر، وفوائد وشوارد، وأمثال وقصص، وسكبت فيها عصارة ما وصل إليه اللامعون، من وراء القلب المفجوع، والروح المنهكة، والنفس الحزينة البائسة، وهذه التجارب تقول للإنسان: أبشر واسعد، وتفاءل واهدأ، وعش الحياة كما هي، طيبة رضية بهيجة.','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '3','bookname'=>'Hello, World! My Body','photo'=>'9781524766368.jpg','price'=>400.00,'details'=>'Little ones are fascinated by their eyes, ears, nose, fingers, and toes. Told in clear and easy terms and featuring bright, cheerful illustrations, this board book teaches toddlers all about the human body, with shapes, sizes, colors, and super-simple facts. Full color.','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '3','bookname'=>'A Place to Stay','photo'=>'s-l500.jpg','price'=>600,'details'=>'An expertly written, child-centred text which can be used to explore the many different traumas that force families into homelessness and to seek places of sanctuary" - Amnesty International UK This simple, touching picture book shows readers a women`s shelter through the eyes of a young girl, who with her mother`s help,','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '4','bookname'=>'The Design of Everyday Things','photo'=>'17290807.jpg','price'=>600,'details'=>'The Art of Doing Science and EngineeringRichard Hamming, 1997The Design of Everyday ThingsDon Norman, 1988The Design of Everyday ThingsThe Design of Everyday Things is a best-selling book by cognitive scientist and usability engineer Donald Norman. Originally published in 1988 with the title The Psychology of Everyday Things, it is often referred to by the initialisms POET and DOET" - Amnesty International UK This simple, touching picture book shows readers a women`s shelter through the eyes of a young girl, who with her mother`s help,','pdf'=>' Administration.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '4','bookname'=>'The Art of Doing Science and Engineering','photo'=>'images11.jpg','price'=>700,'details'=>'The Art of Doing Science and Engineering is a book by American mathematician Richard Hamming. The book comes from a course Hamming taught at the Naval Postgraduate School in Monterey, California. The book was originally published in 1997 by Gordon & Breach. It was republished in 2020 by Stripe Press." - Amnesty International UK This simple, touching picture book shows readers a women`s shelter through the eyes of a young girl, who with her mother`s help,','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '10','bookname'=>'The Mythical Man-Month','photo'=>'images55.jpg','price'=>600,'details'=>'The Mythical Man-Month: Essays on Software Engineering is a book on software engineering and project management by Fred Brooks first published in 1975, with subsequent editions in 1982 and 1995. Its central theme is that adding manpower to a software project that is behind schedule delays it even longer.','pdf'=>'software.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '9','bookname'=>'Computer Engineering ','photo'=>'download (1).jpg','price'=>600,'details'=>'CE for Big Babies is the next step in continuing education, and putting you and your kids in the good graces of the General AI that is sure to take over the world. The book picks up where the original CE for Babies left off. And, like the first book, its way too short with six pages. It explores D-Latches, a Shift Register, a Multiplexer, a Decoder, and reading and writing from Addressable Memory.','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '5','bookname'=>'The Forgotten Firs','photo'=>'9781538705483_p0_v2_s600x595.jpg','price'=>600,'details'=>'THE FORGOTTEN FIRST chronicles the lives of four incredible men, the racism they experienced as Black players entering a segregated sport, the burden of expectation they carried, and their many achievements, which would go on to affect football for generations to come.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '5','bookname'=>'The Blood and Guts','photo'=>'9781538723746_p0_v2_s600x595.jpg','price'=>600,'details'=>'There is no profession in sports like the NFL tight end. None. You must mash 320-pound defensive ends in the run game. You must twist your torso at impossible angles to make acrobatic catches downfield in the pass game. You must have a certain element of crazy to you, too. The tight end is a blend of brain and brawn and bruises…so many bruises. BLOOD AND GUTS tracks the fascinating rise of this position one tight end at a time, from Mike Ditka and John Mackey in the 60s to Rob Gronkowski today.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '6','bookname'=>'Project Hail Mary','photo'=>'9780593135228_p0_v3_s600x595.jpg','price'=>690,'details'=>'An irresistible interstellar adventure as only Andy Weir could deliver, Project Hail Mary is a tale of discovery, speculation, and survival to rival The Martian—while taking us to places it never dreamed of going.','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '6','bookname'=>'History of India','photo'=>'s-l96 (7).jpg','price'=>900,'details'=>'Incredible India is the slogan of Indias official tourism campaign-and its true!India has an amazing history, from some of the worlds earliest civilizations to its contemporary high-tech culture and a huge diversity of religions, arts, and people.','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '7','bookname'=>'The Bent Pyramid','photo'=>'tbp500.jpg','price'=>600,'details'=>'The world has descended into a post-modern quagmire of quotas, affirmative action, mob rule and degeneracy. High in the mountains of North Carolina lies “The Ark,” in which are gathered a select coterie of individuals from varying fields and backgrounds, united only by their intelligence and desire to be sequestered from the hellish society beyond the complex’s walls.','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '7','bookname'=>'Art and Illusion','photo'=>'images.png','price'=>650,'details'=>'A groundbreaking account of perception and art, from one of the twentieth century’s most important art historiansE. H. Gombrich is widely considered to be one of the most influential art historians of the twentieth century, and Art and Illusion is generally agreed to be his most important book','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '8','bookname'=>'Little Book of Dior','photo'=>'images (1).png','price'=>610,'details'=>'Little Book of Dior is the pocket-sized and beautifully illustrated story of over 70 years of opulent fashion.Christian Diors spectacular rise to the upper echelons of the Parisian fashion world is one of the most compelling stories of twentieth-century fashion.','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '8','bookname'=>'Little Book of Chanel','photo'=>'images (17).jpg','price'=>690,'details'=>'Little Book of Chanel is the pocket-sized and beautifully illustrated story of the most celebrated fashion designer in history. Chronicling the life and legacy of Coco Chanel, one of fashions most influential couturiers, this gorgeous book offers a fascinating account of Chanels evolution and innovation.','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '9','bookname'=>'Artificial Intelligence','photo'=>'images (25).jpg','price'=>610,'details'=>'This book provides valuable information on effective, state-of-the-art techniques and approaches for governments, students, researchers, practitioners, entrepreneurs and teachers in the field of artificial intelligence (AI)','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '2', 'cat_id' => '3','bookname'=>'System Design ','photo'=>'images (41).jpg','price'=>600,'details'=>'This book can be seen as a sequel to the book: System Design Interview - An Insiders Guide. It covers a different set of system design interview questions and solutions. Although reading Volume 1 is helpful, it is not required.','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
  
           
           
           ['author_id' => '3', 'cat_id' => '1','bookname'=>'Cujo Paperback Edition','photo'=>'cujo.jpg','price'=>400.00,'details'=>'The classic tale of terror that “hits the jugula (The New York Times) from #1 New York Times bestselling author and master storyteller Stephen King—now featuring a stunning vintage cover','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '1','bookname'=>'Salem`s Lot','photo'=>'salem2024.jpg','price'=>700.00,'details'=>'Author Ben Mears returns to his childhood home of Jerusalem’s Lot only to discover his hometown is being preyed upon by a bloodthirsty vampire. Written and directed by Gary Dauberman, and based on Stephen King`s 1975 novel Salem`s Lot, the film stars Lewis Pullman, Makenzie Leigh, Bill Camp, Pilou Asbæk, Alfre Woodard, and William Sadler.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '2','bookname'=>'بداية ونهاية','photo'=>'5954846.jpg','price'=>750.00,'details'=>'قد يلفت انتباهك اسم الرواية بداية ونهاي ، ويتركك حائرًا متسائلًا، بداية ماذا؟ ونهاية ماذا؟ وسرعان ما ستتبدد تلك التّساؤلات من خلال سير الأحداث، فتدرك أنّ اسم الرّواية يختصر قصّتنا في كلمتين، ويضعها في إطار مُتقن، رسم كاتبنا من خلاله أحداث قصّته، موضّحا أنّ النّهاية لتلك القصّة ما هي إلّا المصير المحتوم لبدايتنا، فالبداية كانت بالموت والنّهاية مع الموت، وما بينهما ما هو إلّا مجموعة من التّفاصيل والأحداث تتناول شخصيّات القصّة و تضحياتها، كيف بدأت كلّ منها؟ وكيف انتهت؟ هذا ما سيعرضه لنا الكاتب بإتقان محكم ونسيج متقن، فقد صال وجال في بحور اللّغة وألوانها، ممّا لن يدع مجالا للشّكّ في نفسك بأنّ ما ينقله هو صورة طبق الأصل لواقع نحياه، وستجد نفسك وقد ارتبطت بأبطاله وألفتهم، حتى بتّ تحيا معهم، فمصابهم مصابنا، وحزنهم حزننا، بكينا كما بكوا، وضحكنا حين ضحكوا.','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '2','bookname'=>'مشاغب','photo'=>'196930486.jpg','price'=>800.00,'details'=>'مجموعة قصصية متنوعة تجمع ما بين القصة الساخرة، الاجتماعية، الرعب، وحتى القصص المبنية على أحداث حقيقية','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '3','bookname'=>'The Book of Dede Korkut','photo'=>'103093.jpg','price'=>100.00,'details'=>'The Book of Dede Korkut is a collection of twelve stories set in the heroic age of the Oghuz Turks, a nomadic tribe who had journeyed westwards through Central Asia from the ninth century onwards. The stories are peopled by characters as bizarre as they are unforgettable: Crazy Karchar, whose unpredictability requires an army of fleas to manage it','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '3','bookname'=>'كليلة ودمنة','photo'=>'2498952.jpg','price'=>100.00,'details'=>'مجموعة حكايات من الأساطير على لسان الحيوانات والطيور.','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '4','bookname'=>'An Introduction to Engineering','photo'=>'images22.jpg','price'=>100.00,'details'=>'This reader-friendly approach helps you develop the strong problem-solving skills and solid foundation in fundamental principles you need to become an analytical, detail-oriented and creative engineer','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '4','bookname'=>'The existential pleasures ','photo'=>'images33.jpg','price'=>200.00,'details'=>'Humans have always sought to change their environment-building houses, monuments, temples, and roads. In the process, they have remade the fabric of the world into newly functional objects that are also works of art to be admired','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '5','bookname'=>'Why We Love Football','photo'=>'9780593475522_p0_v2_s600x595.jpg','price'=>150.00,'details'=>'This is the best kind of sports writing. Entertaining, enlightening, heartbreaking, hilarious, and always fascinating, these stories of the sport offer a panoramic look across its history. From hidden gems and classic tales to famous moments told from previously unheard perspectives, this book is the football book for even its most ardent fans. ','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '5','bookname'=>'Theres Always This Year','photo'=>'9780593448793_p0_v1_s600x595.jpg','price'=>800.00,'details'=>'There’s Always This Year is a triumph, brimming with joy, pain, solidarity, comfort, outrage, and hope. No matter the subject of his keen focus—whether it’s basketball, or music, or performance—Hanif Abdurraqib’s exquisite writing is always poetry, always profound, and always a clarion call to radically reimagine how we think about our culture, our country, and ourselves. ','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '6','bookname'=>'The Fourth Political','photo'=>'4pt-leatherbound.jpg','price'=>100.00,'details'=>'The Fourth Political Theory, argues that modern political systems have evolved from three primary ideologies: liberalism, Marxism, and fascism. While Marxism and fascism have faded into history, liberalism has become so pervasive that it is no longer recognised as an ideology. Dugin contends that this dominance alienates and destroys the diversity of human cultures. ','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '6','bookname'=>'Guns, Germs, and Steel','photo'=>'images (2).jpg','price'=>130.00,'details'=>'Guns, Germs, and Steel: The Fates of Human Societies is a 1997 transdisciplinary nonfiction book by the American author Jared Diamond ','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '7','bookname'=>'Design As Art','photo'=>'images (9).jpg','price'=>110.00,'details'=>'How do we see the world around us? The Penguin on Design series includes the works of creative thinkers whose writings on art, design and the media have changed our vision forever. Bruno Munari was among the most inspirational designers of all time, ','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '7','bookname'=>'Color','photo'=>'images (10).jpg','price'=>190.00,'details'=>'In this vivid and captivating journey through the colors of an artists palette, Victoria Finlay takes us on an enthralling adventure around the world and through the ages, illuminating how the colors we choose to value have ','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '8','bookname'=>'Fashion, New Edition','photo'=>'images (2).png','price'=>140.00,'details'=>'The definitive guide to the history of fashion.From Ancient Egypt and Marie Antionette to Alexander McQueen and Chanel, this visually stunning fashion design book charts the evolution of clothing and shows how every generation reinvents fashion ','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '8','bookname'=>'Fashioning James Bond','photo'=>'images (18).jpg','price'=>120.00,'details'=>'Fashioning James Bond is the first book to study the costumes and fashions of the James Bond movie franchise, from Sean Connery in 1962s Dr No to Daniel Craig in Spectre (2015) ','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '9','bookname'=>'Deep Learning','photo'=>'images (26).jpg','price'=>140.00,'details'=>'An introduction to a broad range of topics in deep learning, covering mathematical and conceptual background, deep learning techniques used in industry, and research perspectives. ','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '9','bookname'=>'Artificial Intelligence ','photo'=>'images (27).jpg','price'=>160.00,'details'=>'Cyber-solutions to real-world business problems Artificial Intelligence in Practice is a fascinating look into how companies use AI and machine learning to solve problems. Presenting 50 case studies of actual situations, ','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '10','bookname'=>'A Philosophy of Software  ','photo'=>'images (39).jpg','price'=>190.00,'details'=>'how to decompose complex software systems into modules (such as classes and methods) that can be implemented relatively independently. The book first introduces the fundamental problem in software design, which is managing complexity. ','pdf'=>'software.pdf','statuse'=>'published'],
           ['author_id' => '3', 'cat_id' => '10','bookname'=>'Introduction to Algorithms','photo'=>'images (40).jpg','price'=>130.00,'details'=>'Introduction to Algorithms is a book on computer programming by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein. The book is described by its publisher as "the leading algorithms text in universities worldwide as well as the standard reference for professionals ','pdf'=>'software.pdf','statuse'=>'published'],
            
           
           ['author_id' => '5', 'cat_id' => '1','bookname'=>'LITTLE FIRES EVERYWHERE','photo'=>'Little.jpg','price'=>100.00,'details'=>'In Shaker Heights, a placid, progressive suburb of Cleveland, everything is planned – from the layout of the winding roads, to the colors of the houses, to the successful lives its residents will go on to lead. And no one embodies this spirit more than Elena Richardson, whose guiding principle is playing by the rules.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '1','bookname'=>'OUR MISSING HEARTS','photo'=>'OMH.jpeg','price'=>500.00,'details'=>'Twelve-year-old Bird Gardner lives a quiet existence with his loving but broken father, a former linguist who now shelves books in a university library. Bird knows to not ask too many questions, stand out too much, or stray too far. For a decade, their lives have been governed by laws written to preserve “American culture” in the wake of years of economic instability and violence.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '2','bookname'=>'ماذا علمتني الحياة؟','photo'=>'3508012.jpg','price'=>900.00,'details'=>'بفكر عميق و قلم شديد السلاسة- يحول امين سيرته الذاتية الى اداة سبر للمجتمع الذي نشأ فيه ..فأذا به يقارن بين ظروف نشاته و ظروف نشأة والده و من ثم اولاده و احفاده ، و يرجع الملاحظات الخاصة ( التي قد تكون عادية و يعتبرها البعض عابرة) الى ظواهرها و اصولها العامة فيربط الخاص بالعام و يتحول الفرد الى مرآة عاكسة لمجتمعه..و يتحول كتاب السيرة الذاتية الى كتاب يتناول حياة اجيال بكاملها.','pdf'=>'ukuza.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '2','bookname'=>'أنا قادم أيها الضوء','photo'=>'63943207.jpg','price'=>400.00,'details'=>'هذا كتاب مُلهم وإنساني، يحمل في كلماته روح المقاتل وعزيمة المثابر وحكمة المتأمل، لا يحكي فيه محمد أبو الغيط عن المعركة الشرسة بينه وبين أبغض أمراض العصر، بل يحكي عن العشرات والعشرات من التفاصيل في جوانب الحياة المختلفة، تتماس وتبتعد عن بعضها البعض لكن يبقى هو وروحه التي لا تقهر وإرادته البشرية الهائلة وإنسانيته اللامحدودة، هي العوامل المشتركة بين كل تلك الحكايات.يقول محمد أبو الغيط عن الكتاب','pdf'=>'ukuza.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '3','bookname'=>'The World Is Awaiting You','photo'=>'s-l96 (1).jpg','price'=>400.00,'details'=>'From beloved Marianne Richmond, who has touched the lives of more than nine million readers for nearly three decades, THE WORLD IS AWAITING YOU celebrates the excitement of a new beginning and how--through hands, mind, hear','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '3','bookname'=>'I Choose To Try Again','photo'=>'s-l96 (2).jpg','price'=>300.00,'details'=>'In this rhyming story, Kiara learns how to keep going even when things get too hard. Through colorful illustrations and rhythmic rhymes, Kiara reflects on her mistakes and realizes that mistakes help her grow. Instead of avoiding them, she learns from them so she can improve. Do you want your child to learn about perseverance and diligence?','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '4','bookname'=>'Skunk Works','photo'=>'images.jpg','price'=>300.00,'details'=>'This classic history of Americas high-stakes quest to dominate the skies is a gripping technothriller in which the technology is real (New York Times Book Review). From the development of the U-2 to the Stealth fighter, Skunk Works is the true story of Americas most secret and successful aerospace operation','pdf'=>'Administration.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '4','bookname'=>'Engineering and  Minds  ','photo'=>'images (1).jpg','price'=>300.00,'details'=>'Engineering and the Minds Eye is a book by Eugene S. Ferguson, an engineer and historian of science and technology. It was published by MIT Press. In it, Ferguson discusses the importance of the minds eye for the practicing engineer, including spatial visualization and visual thinking.','pdf'=>'Administration.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '5','bookname'=>'Got Your Answers','photo'=>'9781368108584_p0_v1_s600x595.jpg','price'=>390.00,'details'=>'Armed with a wealth of knowledge and fandom experience, Greeny and Hembo tackle the 100 most-debated questions in the sports-talk world and provide 100 lists that will tell you who is the best of the best in football, basketball, baseball, hockey, boxing, and more. What is the most coveted trophy in all of sports? Who is the most clutch in Game 7? Which ballpark has the most bizarre concessions? And why is Rocky without a doubt the best sports movie of all time?','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '5','bookname'=>'Behind the Mask','photo'=>'9781778402333_p0_v2_s600x595.jpg','price'=>190.00,'details'=>'The careers here cover the last half-century of professional hockey from the personal struggles of Roger Crozier and Ed Giacomin on their way to stardom in the 1960s, to the recent brilliance of Carey Price, whose character blends stoicism with a deep warmth and pride in his Indigenous background.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '6','bookname'=>'The Devil in the White ','photo'=>'images (3).jpg','price'=>330.00,'details'=>'The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America is a 2003 historical non-fiction book by Erik Larson presented in a novelistic style.','pdf'=>'Argentina.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '6','bookname'=>'The Guns of August','photo'=>'images (4).jpg','price'=>390.00,'details'=>'The Guns of August is a 1962 book centered on the first month of World War I written by Barbara W. Tuchman. After introductory chapters, Tuchman describes in great detail the opening events of the conflict. The books focus then becomes a military history of the contestants, chiefly the great powers','pdf'=>'Argentina.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '7','bookname'=>'On Photography','photo'=>'images (11).jpg','price'=>350.00,'details'=>'On Photography is a 1977 collection of essays by American writer Susan Sontag. The book originated from a series of essays Sontag published in The New York Review of Books between 1973 and 1977. In On Photography, Sontag examines the history and contemporary role of photography in society.','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '7','bookname'=>'Steal Like an Artist','photo'=>'images (12).jpg','price'=>390.00,'details'=>'Steal Like an Artist: 10 Things Nobody Told You About Being Creative is a book on coming up with creative ideas written by Austin Kleon and published in 2012 from Workman Publishing.','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '8','bookname'=>'How to Wear Everything','photo'=>'images (19).jpg','price'=>310.00,'details'=>'At last—a fun, chic, no-nonsense guide to getting dressed.What we wear matters. It matters because looking and therefore feeling like yourself is essential. Clothes can make the difference between a good day and a bad day.','pdf'=>'Dressing.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '8','bookname'=>'A Life in Fashion','photo'=>'images (20).jpg','price'=>320.00,'details'=>'Fashion and creative director Sunita Kumar Nair presents Carolyn Bessette Kennedy: A Life in Fashion, which pays homage to the style icon’s timeless, distinguished beauty, and legacy in the first book of its kind','pdf'=>'Dressing.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '9','bookname'=>'Learning from Data','photo'=>'images (28).jpg','price'=>380.00,'details'=>'This is a textbook to help readers understand the steps that lead to deep learning. Linear algebra comes first especially singular values, least squares, and matrix factorizations.','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '9','bookname'=>'Storytelling with Data','photo'=>'images (29).jpg','price'=>350.00,'details'=>'Dont simply show your data—tell a story with it! Storytelling with Data teaches you the fundamentals of data visualization and how to communicate effectively with data.','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '10','bookname'=>'Essentials of Software Engineering','photo'=>'images (37).jpg','price'=>390.00,'details'=>'Each new print copy includes Navigate 2 Advantage Access that unlocks a comprehensive and interactive eBook, student practice activities and assessments, a full suite of instructor resources, and learning analytics reporting tools','pdf'=>'software.pdf','statuse'=>'published'],
            ['author_id' => '5', 'cat_id' => '10','bookname'=>'Programming Pearls','photo'=>'images (38).jpg','price'=>320.00,'details'=>'Just as natural pearls grow from grains of sand that irritate oysters, programming pearls have grown from real problems that have irritated real programmers. With origins beyond solid engineering, in the realm of insight and creativity','pdf'=>'software.pdf','statuse'=>'published'],
           
            ['author_id' => '4', 'cat_id' => '1','bookname'=>'The Water Dancer','photo'=>'The_Water_Dancer_(Coates_novel).png','price'=>500.00,'details'=>'It is a surrealist story set in the pre-Civil War South, concerning a superhuman protagonist named Hiram Walker who possesses a photographic memory, but who cannot remember his mother. He learns he has a special ability known as conduction, with which he is able to transport people—including himself—over long distances. Conduction is powered by his memories and storytelling, and can fold the Earth like fabric, allowing travel across large areas via waterways.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '1','bookname'=>'The New Yorker','photo'=>'Original_New_Yorker_cover.png','price'=>300.00,'details'=>'The New Yorker is an American magazine featuring journalism, commentary, criticism, essays, fiction, satire, cartoons, and poetry. It was founded on February 21, 1925, by Harold Ross and his wife Jane Grant, a reporter for The New York Times. Together with entrepreneur Raoul H. Fleischmann, they established the F-R Publishing Company and set up the magazine`s first office in Manhattan. Ross remained the editor until his death in 1951, shaping the magazine`s editorial tone and standards.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '2','bookname'=>'الأيام','photo'=>'3371137.jpg','price'=>200.00,'details'=>'كتابأشهر من أن يعرّف، وهو بجانب قيمته الأدبية الرفيعة باعتباره طرازاً فريداً من السير الذاتية لشخصية أدبيه قل أن يجود الزمان بمثلها، وصدق وعذوبة وطلاوة أسلوب، وهى مزايا يكاد يستأثر بها، فإن هذا العمل يمهد لإحاطة القارئ بدنيا طه حسين والروافد الفكرية والثقافية التى شكلت مذهبه ومنهجه.','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '2','bookname'=>'وا إسلاماه','photo'=>'5889987.jpg','price'=>900.00,'details'=>'هذه قصة تجلو صفحة رائعة من صفحات التاريخ المصري فى عهد من اخصب عهوده واحلفها بالحوادث الكبرى والعبر الجلى . يطل منها القارئ على المجتمع الإسلامي في أهم بلاده من نهر السند إلى نهر النيل وهو يستيقظ من سباته الطويل على صليل سيوف المغيرين عليه من تتار الشرق وصليبيى الغرب، فيهب للكفاح والدفاع عن أنفس ما عنده من تراث الدين والدنيا.','pdf'=>'ukuza.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '3','bookname'=>'Bobby`s Story','photo'=>'s-l96.jpg','price'=>400.00,'details'=>'When Bobby learns more about homelessness, he wants to tell his classmates and help make a difference. But everyone is busy and distracted by their own activities. Can he find a way to tell this important story?','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '3','bookname'=>'What Are You Feeling?','photo'=>'s-l96 (3).jpg','price'=>980.00,'details'=>'What Are You Feeling? is the first in a series of books that aims to develop emotional literacy for children aged 5-8 years.It is a book about finding interesting words for interesting feelings. It explores what lots of feeling words really mean and which words best describe the many feelings a child may have.The book discusses 20 different feelings from happy to mischievous. The child is encouraged to identify these feelings in ways that are healthy and easy to understand.','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '4','bookname'=>'Engineering Principles','photo'=>'download.jpg','price'=>980.00,'details'=>' This book is about the role of some engineering principles in our everyday lives. Engineers study these principles and use them in the design and analysis of the products and systems with which they work. The same principles play basic and influential roles in our everyday lives as well. Whether the concept of entropy, the moments of inertia, the natural frequency, the Coriolis acceleration, or the electromotive force, the roles and effects of these phenomena are the same in a system designed by an engineer or created by nature','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '4','bookname'=>'DESIGN AND DETAILINGOF FLAT SLAB','photo'=>'1.jpg','price'=>990.00,'details'=>'a reinforced concrete slab supported directly by concrete columns without the use of beams. allows standardized structural members and prefabricated sections to be integrated into the design for ease of construction. this process will make the structure more buildable, reduce the number of site workers and increase the productivity at the site.','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '5','bookname'=>'The Race to the Future','photo'=>'9781324094913_p0_v2_s600x595.jpg','price'=>980.00,'details'=>'A gripping, immersive narrative of the race, The Race to the Future sets the drivers’ derring-do (and occasional cheating) against the backdrop of a larger geopolitical and technological race to the future. Interweaving events from the fall of the Qing dynasty to the departure of the horse economy and the rise of gendered marketing, St. Clair shows how the Peking-to-Paris provided an impetus for profound social, cultural, and industrial change, while masterfully capturing the mounting tensions between nations and empires—all building up to the cataclysmic event that changed everything: the First World War.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '5','bookname'=>'Playing from the Rough','photo'=>'9781668005972_p0_v4_s600x595.jpg','price'=>1000.00,'details'=>'Bringing together golf, civil rights and a rags-to-riches personal narrative, this is the story of one mans journey through golf in America, and the history woven into it. With a good sense of humor and uplifting message, its about so much more than just golf.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '6','bookname'=>'The Great Divergence','photo'=>'images (5).jpg','price'=>990.00,'details'=>'A landmark comparative history of Europe and China that examines why the Industrial Revolution emerged in the WestThe Great Divergence sheds light on one of the great questions of history: Why did sustained industrial growth begin in Northwest Europe?','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '6','bookname'=>'Empires of the Atlantic World','photo'=>'images (6).jpg','price'=>920.00,'details'=>'This epic history compares the empires built by Spain and Britain in the Americas, from Columbus’s arrival in the New World to the end of Spanish colonial rule in the early nineteenth century','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '7','bookname'=>'Monet or the Triumph ','photo'=>'images (13).jpg','price'=>980.00,'details'=>'Contains all of Monets 2000 pictures, as well as almost 100 rediscovered canvases. The first volume acts as an introduction to Monets life, and the other three present his complete work','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '7','bookname'=>'Art Matters','photo'=>'images (14).jpg','price'=>970.00,'details'=>'A stunning and timely creative call-to-arms combining four extraordinary written pieces by Neil Gaiman illustrated with the striking four-color artwork of Chris Riddell.','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '8','bookname'=>'Sneaker Freaker','photo'=>'images (21).jpg','price'=>910.00,'details'=>'Every Sneaker Story Worth Telling! A 15 year anthology of cult magazine Sneaker Freaker. When self-acclaimed Sneakerhead Simon "Woody" Wood decided to pursue his love of sneakers--and freebie footwear--with a publication, the mighty Sneaker Freaker was born','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '8','bookname'=>'Black in Fashion','photo'=>'images (22).jpg','price'=>980.00,'details'=>'A stunning and comprehensive look at the indelible contribution of Black designers, models, scene-makers, and stylists to fashion history, from the bible of fashion--WWD.','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '9','bookname'=>'Machine Learning Design Patterns','photo'=>'images (30).jpg','price'=>910.00,'details'=>'The design patterns in this book capture best practices and solutions to recurring problems in machine learning. The authors, three Google engineers, catalog proven methods to help data scientists tackle','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '9','bookname'=>'Data Scientists','photo'=>'images (31).jpg','price'=>920.00,'details'=>'Statistical methods are a key part of data science, yet very few data scientists have any formal statistics training. Courses and books on basic statistics rarely cover the topic from a data science perspective. ','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '10','bookname'=>'Code','photo'=>'images (3).png','price'=>910.00,'details'=>'The Hidden Language of Computer Hardware and Software is a book by Charles Petzold that seeks to teach how personal computers work at a hardware and software level','pdf'=>'software.pdf','statuse'=>'published'],
           ['author_id' => '4', 'cat_id' => '10','bookname'=>'Software Engineering','photo'=>'images (36).jpg','price'=>970.00,'details'=>'Designed for the introductory programming course or the software engineering projects course offered in departments of computer science. This book serves as a cookbook for software engineering, presenting the subject as a series of steps that the student can apply to complete a software project.','pdf'=>'software.pdf','statuse'=>'published'],

          
           
           ['author_id' => '6', 'cat_id' => '1','bookname'=>'The Shawshank Redemption 30th ','photo'=>'shawshank.jpg','price'=>100.00,'details'=>'The Shawshank Redemption is Kings most popular movie adaptations and among the most frequently viewed films of all time. This standalone edition of King’s novella, retitled The Shawshank Redemption to capture new King readers, has a new cover with a film still featuring stars Morgan Freeman and Tim Robbins for the 30th anniversary of the Best Picture Academy Award nominee.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '1','bookname'=>'The City and Its Uncertain Walls','photo'=>'9780593801970.jpg','price'=>900.00,'details'=>'From the bestselling author of Norwegian Wood and Hard-Boiled Wonderland and the End of the World comes a love story, a quest, an ode to books and to the libraries that house them, and a parable for our peculiar times.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '1','bookname'=>'The Monkey','photo'=>'the_monkey_film_poster.jpg','price'=>400.00,'details'=>'After stumbling upon their father`s vintage toy monkey in the attic, twin brothers Hal and Bill witness a string of horrifying deaths unfolding around them. In an attempt to leave the haunting behind, the brothers opt to discard the monkey and pursue separate paths over time. However, when the inexplicable deaths resurface, the brothers are compelled to reconcile and embark on a mission to permanently eliminate the cursed toy.Written and direct , Rohan Campbell and Sarah Levy.','pdf'=>'the-story-of-doctor-dolittle.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '3','bookname'=>'My Grandpa, My Tree, and Me by Troup, Roxanne','photo'=>'s-l96 (6).jpg','price'=>100.00,'details'=>'In this moving tale about the depths of love and care a grandfather and granddaughter have for one another, author Roxanne Troup and artist Kendra Binney deliver a timeless story sure to become a classic. Of all the trees in Grandpa`s orchard, one tree is his favorite--a pecan tree, planted for his granddaughter on the day she was born','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '3','bookname'=>'Mommy is the Mayor ','photo'=>'s-l96 (5).jpg','price'=>800.00,'details'=>'Mommy is the Mayor is a narrative about a city mayor`s role. Seen through the eyes of children, it opens up the world to convey the impact local government has on their everyday lives.','pdf'=>'2504-Lady-Needed-Space-FKB.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '4','bookname'=>'Airport Planning & Management','photo'=>'1 (1).jpg','price'=>700.00,'details'=>'It is often said that managing an airport is like being mayor of a city. Similar to a city, an airport is comprised of a huge variety of facilities, systems, users, workers, rules, and regulations. Also, just as cities thrive on trade and commerce with other cities, airports are successful in part by their ability to successfully be the location where passengers and cargo travel to and from other airports.','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '4','bookname'=>'Design and Calculation','photo'=>'1 (2).jpg','price'=>220.00,'details'=>'This excel sheet calculate reinforcment and dimensions for columns ','pdf'=>'Administration.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '5','bookname'=>'A Walk in the Park','photo'=>'9781501183058_p0_v8_s600x595.jpg','price'=>290.00,'details'=>'The ensuing ordeal, which lasted more than a year, revealed a place that was deeper, richer, and far more complex than anything the two men had imagined—and came within a hair’s breadth of killing them both. They struggled to make their way through a vertical labyrinth of thousand-foot cliffs and crumbling ledges where water is measured out by the teaspoon and every step is fraught with peril—and where, even today, there is still no trail along the length of the country’s best-known and most iconic park.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '5','bookname'=>'The Football 100','photo'=>'9780063329096_p0_v3_s600x595.jpg','price'=>230.00,'details'=>'At The Athletic, home to the best newsroom in sports, this question would become a labor of love for dozens of the best football writers on the planet, including Mike Sando and Dan Pompei. Over the course of 100 riveting profiles based on many hundreds of interviews with players, coaches, broadcasters, and others, this is a penetrating look at the greatest players to ever don cleats and pads, as well as a view from the trenches of the harsh realities of a brutal game. 100 photographs throughout the text offer testament to both the glory and the physical toll of football.','pdf'=>'American Football, Tutorials Point.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '6','bookname'=>'The decision to use the atomic','photo'=>'images (7).jpg','price'=>200.00,'details'=>'One of the most controversial issues absorbing America today: Was it necessary to drop the atomic bombs on Hiroshima and Nagasaki? Fifty years after the fateful summer of 1945, we are still debating Harry Trumans decision','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '6','bookname'=>'Gender  history','photo'=>'images (8).jpg','price'=>200.00,'details'=>'This landmark work from a renowned feminist historian is a foundational demonstration of the uses of gender as a conceptual tool for cultural and historical analysis.','pdf'=>'Argentina.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '7','bookname'=>'Great Women Painters','photo'=>'images (15).jpg','price'=>290.00,'details'=>'A sumptuous survey of over 300 women painters and their work spanning almost five centuries Great Women Painters is a groundbreaking book that reveals a richer and more varied telling of the story of painting','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '7','bookname'=>'The Invisible Art','photo'=>'images (16).jpg','price'=>200.00,'details'=>'Understanding Comics: The Invisible Art is a 1993 non-fiction work of comics by American cartoonist Scott McCloud. It explores formal aspects of comics, the historical development of the medium, its fundamental vocabulary,','pdf'=>'Classical Academy.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '8','bookname'=>'The Secret Lives of Colour','photo'=>'images (23).jpg','price'=>290.00,'details'=>'The Secret Lives of Colour is a 2016 non-fiction book by British writer Kassia St. Clair which explores the cultural and social history of colours. The book, which is based on a column St. Clair writes for British magazine Elle Decoration, is organized in a series of chapters by color, arranged from white to black','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '8','bookname'=>'Skincare','photo'=>'images (24).jpg','price'=>200.00,'details'=>'The Ultimate No-Nonsense Guide. Whether you are a skincare pro or overwhelmed by information, Skincare: The New Edit covers where to start, how to build a routine, ingredients to look for and things to avoid, whatever your age, skin concerns or budget.','pdf'=>'Dressing.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '9','bookname'=>'R for Data Science','photo'=>'images (32).jpg','price'=>290.00,'details'=>'R for Data Science is perfect for anyone starting with data science projects in R and provides practical exercises to solidify learning. The book emphasizes ','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '9','bookname'=>'Data Science and AI','photo'=>'images (33).jpg','price'=>210.00,'details'=>'A comprehensive overview of the various fields of application of data science and artificial intelligence.- Case studies from practice to make the described concepts tangible','pdf'=>'learn-scratch-lesson-1.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '10','bookname'=>'Code Complete','photo'=>'images (34).jpg','price'=>600.00,'details'=>'Code Complete is a software development book, written by Steve McConnell and published in 1993 by Microsoft Press, encouraging developers to continue past code-and-fix programming and the big design up front and waterfall models.','pdf'=>'software.pdf','statuse'=>'published'],
           ['author_id' => '6', 'cat_id' => '10','bookname'=>'Design Patterns','photo'=>'images (35).jpg','price'=>500.00,'details'=>'Design Patterns: Elements of Reusable Object-Oriented Software is a software engineering book describing software design patterns. The book was written by Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides, with a foreword by Grady Booch.','pdf'=>'software.pdf','statuse'=>'published'],
 





 

]        );



    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('books');
    }
};
